# Generated by Django 4.2.16 on 2024-12-20 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.halls'),
        ),
    ]
