# Generated by Django 4.2.16 on 2024-12-20 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_city_hall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='Hotel',
        ),
        migrations.RemoveField(
            model_name='city',
            name='hall',
        ),
        migrations.AddField(
            model_name='hotels',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.city'),
        ),
    ]
