# Generated by Django 4.2.16 on 2024-12-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_remove_city_hotel_remove_city_hall_hotels_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
