# Generated by Django 4.2.16 on 2024-11-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('trainer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(default='example@email.com', max_length=50)),
                ('nationality', models.CharField(max_length=255)),
                ('residence_location', models.CharField(max_length=255)),
                ('field_of_experties', models.CharField(max_length=255)),
                ('average_rate', models.CharField(max_length=20)),
                ('trainer_category', models.CharField(max_length=20)),
                ('cv', models.FileField(blank=True, null=True, upload_to='pdf')),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('trainer_photo', models.ImageField(blank=True, default='employee_photos/avatar.png', null=True, upload_to='trainers/')),
                ('passport_scan', models.FileField(blank=True, null=True, upload_to='pdf')),
                ('bank_account_number', models.CharField(blank=True, max_length=500, null=True)),
                ('bank_swift_code', models.CharField(blank=True, max_length=500, null=True)),
                ('account_currency', models.CharField(blank=True, max_length=20, null=True)),
                ('account_branch', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
