# Generated by Django 4.2.16 on 2024-12-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_visa_vis_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
