# Generated by Django 4.2.16 on 2024-12-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_visa_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='from_to',
        ),
        migrations.AddField(
            model_name='flight',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_from',
            field=models.CharField(default='Cairo', max_length=255),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_to',
            field=models.CharField(default='Abudhabi', max_length=255),
        ),
    ]
