# Generated by Django 4.2.16 on 2024-12-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_remove_flight_from_to_flight_created_at_flight_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='date',
            new_name='departure_date',
        ),
    ]
