# Generated by Django 5.1.3 on 2024-11-10 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('deparment_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('trainer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(default='example@email.com', max_length=50)),
                ('nationality', models.CharField(max_length=255)),
                ('residence_location', models.CharField(max_length=255)),
                ('field_of_experties', models.CharField(max_length=255)),
                ('average_rate', models.CharField(max_length=20)),
                ('trainer_category', models.CharField(max_length=20)),
                ('cv', models.FileField(blank=True, null=True, upload_to='pdf')),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('trainer_photo', models.ImageField(blank=True, default='employee_photos/default-employee.webp', null=True, upload_to='employee_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('manager', models.BooleanField()),
                ('employee_photo', models.ImageField(blank=True, default='employee_photos/default-employee.webp', null=True, upload_to='employee_photos/')),
                ('location', models.CharField(max_length=50, null=True)),
                ('comilative_points', models.CharField(max_length=20, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.department')),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(default='example@email.com', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('sales_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('feedback', models.FileField(blank=True, null=True, upload_to='pdf')),
                ('invoice', models.FileField(blank=True, null=True, upload_to='pdf')),
                ('dead_line', models.DateField()),
                ('starting_Date', models.DateField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.client')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('proposal_id', models.AutoField(primary_key=True, serialize=False)),
                ('proposal_name', models.CharField(max_length=255)),
                ('dead_line', models.DateField()),
                ('proposal_document', models.FileField(blank=True, null=True, upload_to='pdf')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
            ],
        ),
        migrations.CreateModel(
            name='Request_for_proposal',
            fields=[
                ('rfp_id', models.AutoField(primary_key=True, serialize=False)),
                ('rfp_name', models.CharField(max_length=255)),
                ('dead_line', models.DateField()),
                ('rfp_document', models.FileField(blank=True, null=True, upload_to='pdf')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
            ],
        ),
    ]
