# Generated by Django 5.1.3 on 2024-11-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_asessmentbank_certificate_compitency_hotel_of_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_photo',
            field=models.ImageField(blank=True, default='employee_photos/sara.jpg', null=True, upload_to='employee_photos/'),
        ),
    ]
