# Generated by Django 5.1.3 on 2024-11-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_employee_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number_of_gift',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
