# Generated by Django 5.1.3 on 2024-11-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_course_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_logo',
            field=models.ImageField(blank=True, default='clients/default.png', null=True, upload_to='clients/'),
        ),
    ]
