# Generated by Django 5.1.3 on 2024-11-11 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_client_client_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sales_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='base.employee'),
        ),
    ]
