# Generated by Django 5.1.3 on 2024-11-11 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_client_sales_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sales_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='base.employee'),
        ),
    ]
