# Generated by Django 5.1.3 on 2024-11-11 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_client_sales_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='deparment_name',
            new_name='department_name',
        ),
    ]
