# Generated by Django 5.1.3 on 2024-11-11 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_certificate_certificate_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.certificate'),
        ),
        migrations.AlterField(
            model_name='course',
            name='materials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.material'),
        ),
        migrations.AlterField(
            model_name='course',
            name='number_of_attendees',
            field=models.CharField(blank=True, default='1', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='number_of_gift',
            field=models.CharField(blank=True, default='1', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='trainer_visa_valid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
