# Generated by Django 5.1.3 on 2024-11-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_course_sales_man'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('not confirmed', 'Not Confirmed'), ('confirmed', 'Confirmed'), ('running', 'Running'), ('finished', 'Finished'), ('canceled', 'Canceled'), ('merged', 'Merged')], default='not confirmed', max_length=50),
        ),
    ]
