# Generated by Django 5.1.3 on 2024-11-11 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_course_confirmed_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Sales_man',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='base.employee'),
        ),
    ]
