# Generated by Django 4.2.16 on 2024-11-11 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_course_sales_man'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='registred_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
