# Generated by Django 4.2.16 on 2024-11-12 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_client_registred_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_document', models.FileField(blank=True, null=True, upload_to='pdf')),
                ('invoice_number', models.CharField(max_length=255)),
                ('invoice_status', models.CharField(choices=[('accepted', 'Accepted'), ('issued', 'Issued'), ('paid', 'Paid'), ('waiting papers', 'Waiting Papers')], default='accepted', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='client',
        ),
        migrations.RemoveField(
            model_name='request_for_proposal',
            name='client',
        ),
        migrations.AddField(
            model_name='project',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.proposal'),
        ),
        migrations.AddField(
            model_name='project',
            name='request_for_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.request_for_proposal'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposal_status',
            field=models.CharField(choices=[('recieved', 'Recieved'), ('pricing', 'Pricing'), ('priced', 'Priced'), ('sent', 'Sent')], default='recieved', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='project_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.project_invoice'),
        ),
    ]
