# Generated by Django 4.2.16 on 2024-11-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_project_project_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proposal_name',
            field=models.CharField(blank=True, default=models.CharField(max_length=255), max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rfp_name',
            field=models.CharField(blank=True, default=models.CharField(max_length=255), max_length=255, null=True),
        ),
    ]
