# Generated by Django 4.2.16 on 2024-11-13 13:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_project_proposal_name_alter_project_rfp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='facilitator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.facilitator'),
        ),
        migrations.AlterField(
            model_name='project',
            name='proposal_dead_line',
            field=models.DateField(blank=True, default=datetime.date(2024, 11, 13), null=True),
        ),
    ]
