# Generated by Django 4.2.16 on 2024-11-14 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_course_certificate_certificate_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='materials',
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_status',
            field=models.CharField(blank=True, choices=[('Names sheet recieved', 'Name Ready'), ('Ready for Design', 'Ready For Design'), ('Ready to Print', 'Ready For Print'), ('printed and Ready for Delivery', 'Ready For Delivery'), ('delivered', 'Certificate Delivered')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='certificates_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
        migrations.AddField(
            model_name='course',
            name='maerial_status',
            field=models.CharField(blank=True, choices=[('Receieved', 'Received Material'), ('Ready for Design', 'Ready For Design'), ('Ready to Print', 'Ready For Print'), ('printed and Ready for Delivery', 'Ready For Delivery'), ('Delivred', 'Delivered')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='material_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
        migrations.AlterField(
            model_name='project',
            name='proposal_dead_line',
            field=models.DateField(blank=True, default=datetime.date(2024, 11, 14), null=True),
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
