# Generated by Django 4.2.16 on 2024-11-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_course_materials_course_certificate_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='maerial_status',
            field=models.CharField(blank=True, choices=[('not Receieved', 'Not Recieved'), ('Receieved', 'Received Material'), ('Ready for Design', 'Ready For Design'), ('Ready to Print', 'Ready For Print'), ('printed and Ready for Delivery', 'Ready For Delivery'), ('Delivred', 'Delivered')], default='not Receieved', max_length=40, null=True),
        ),
    ]
