# Generated by Django 4.2.16 on 2024-11-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_course_maerial_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='certificate_status',
            field=models.CharField(blank=True, choices=[('no action', 'No Action'), ('Names sheet recieved', 'Name Ready'), ('Ready for Design', 'Ready For Design'), ('Ready to Print', 'Ready For Print'), ('printed and Ready for Delivery', 'Ready For Delivery'), ('delivered', 'Certificate Delivered')], default='no action', max_length=40, null=True),
        ),
    ]
