# Generated by Django 4.2.16 on 2024-11-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_course_certificate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='attendance_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
        migrations.AddField(
            model_name='course',
            name='feedback',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
    ]
