# Generated by Django 4.2.16 on 2024-11-16 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_course_attendance_file_course_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proposal_dead_line',
            field=models.DateField(blank=True, default=datetime.date(2024, 11, 16), null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trainer_photo',
            field=models.ImageField(blank=True, default='employee_photos/avatar.png', null=True, upload_to='trainers/'),
        ),
    ]
