# Generated by Django 4.2.16 on 2024-11-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_project_proposal_dead_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='points',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
