# Generated by Django 4.2.16 on 2024-11-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_task_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='maerial_status',
            new_name='material_status',
        ),
    ]
