# Generated by Django 4.2.16 on 2024-11-17 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_rename_maerial_status_course_material_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proposal_dead_line',
            field=models.DateField(blank=True, default=datetime.date(2024, 11, 17), null=True),
        ),
    ]
