# Generated by Django 4.2.16 on 2024-11-22 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_project_proposal_dead_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proposal_dead_line',
            field=models.DateField(blank=True, default=datetime.date(2024, 11, 22), null=True),
        ),
    ]
