# Generated by Django 4.2.16 on 2024-11-22 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
        ('base', '0030_alter_project_proposal_dead_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainers.trainer'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainer'),
        ),
        migrations.AlterField(
            model_name='trainers_hotel',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainer'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainer'),
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
