# Generated by Django 4.2.16 on 2024-11-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_course_trainer_alter_flight_trainer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainers_hotel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='trainers_hotel',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='course',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='trainer',
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
        migrations.DeleteModel(
            name='Trainers_hotel',
        ),
        migrations.DeleteModel(
            name='Visa',
        ),
    ]
