# Generated by Django 4.2.16 on 2024-12-10 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_remove_trainers_hotel_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inventory_name',
            field=models.CharField(default='item', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='proposal_dead_line',
            field=models.DateField(blank=True, default=datetime.date(2024, 12, 10), null=True),
        ),
    ]
