# Generated by Django 4.2.16 on 2024-12-18 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_inventory_inventory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proposal_dead_line',
            field=models.DateField(blank=True, default=datetime.date(2024, 12, 18), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='proposal_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('working', 'Working'), ('accepted', 'Accepted'), ('returned', 'Returned')], default='waiting', max_length=20),
        ),
    ]
