# Generated by Django 4.2.16 on 2024-12-20 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_remove_hotels_hall_halls_hotel_alter_hotels_city'),
        ('base', '0039_alter_project_proposal_dead_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='hotel',
        ),
        migrations.AddField(
            model_name='course',
            name='place_of_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.halls'),
        ),
        migrations.DeleteModel(
            name='Hotel_of_course',
        ),
    ]
