# Generated by Django 4.2.16 on 2024-12-21 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_remove_course_hotel_course_place_of_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proposal_dead_line',
            field=models.DateField(blank=True, default=datetime.date(2024, 12, 21), null=True),
        ),
    ]
